# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('category', models.TextField()),
                ('address', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
