# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170212_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.TextField(default='N/A'),
        ),
    ]
