# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
